steps:
# Using dep container from github.com/solo-io/cloud-builders/dep
# This copies files into the proper workspace layout and so must be run before other tasks.
# Subsequent steps must set the $GOPATH env variable.
- name: 'gcr.io/$PROJECT_ID/dep'
  id: 'dep'
  args: ['ensure']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/ext-auth-plugins'

- name: 'gcr.io/$PROJECT_ID/go-make:0.1.12'
  id: 'compare-dependencies'
  args: ['compare-deps']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/ext-auth-plugins'
  - 'GOPATH=/workspace/gopath'
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'BUILD_ID=$BUILD_ID'
  dir: './gopath/src/github.com/solo-io/ext-auth-plugins'

- name: 'gcr.io/$PROJECT_ID/go-make:0.1.12'
  id: 'build-plugins-for-tests'
  args: ['build-plugins-for-tests']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/ext-auth-plugins'
  - 'GOPATH=/workspace/gopath'
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'BUILD_ID=$BUILD_ID'
  dir: './gopath/src/github.com/solo-io/ext-auth-plugins'

- name: 'gcr.io/$PROJECT_ID/ginkgo:0.1.12'
  id: 'test-plugins'
  args: ['-r']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/ext-auth-plugins'
  - 'GOPATH=/workspace/gopath'
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'BUILD_ID=$BUILD_ID'
  dir: './gopath/src/github.com/solo-io/ext-auth-plugins'

- name: 'gcr.io/$PROJECT_ID/go-make:0.1.12'
  id: 'build-plugins'
  args: ['build-plugins']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/ext-auth-plugins'
  - 'GOPATH=/workspace/gopath'
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'BUILD_ID=$BUILD_ID'
  dir: './gopath/src/github.com/solo-io/ext-auth-plugins'

- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login quay.io --username "solo-io+solobot" --password $$QUAY_IO_PASSWORD']
  secretEnv: ['QUAY_IO_PASSWORD']
  id: 'docker-login'

- name: 'gcr.io/$PROJECT_ID/go-make:0.1.12'
  args: ['release-plugins']
  env:
  - 'PROJECT_ROOT=github.com/solo-io/ext-auth-plugins'
  - 'GOPATH=/workspace/gopath'
  - 'TAGGED_VERSION=$TAG_NAME'
  - 'BUILD_ID=$BUILD_ID'
  dir: './gopath/src/github.com/solo-io/ext-auth-plugins'
  id: 'release-plugins'

secrets:
- kmsKeyName: projects/solo-public/locations/global/keyRings/build/cryptoKeys/build-key
  secretEnv:
    QUAY_IO_PASSWORD: CiQABlzmSRx5TcOqbldXa/d/+bkmAfpNAWa3PTS06WvuloZL+vASaQCCPGSGCogonVZVEUNx4G3YJtWi18gSuNx4PvLe08q8xAflTMFkjsyQirAOK3Y2oCvgYwiw/ITcuydjkpMjxDygFyENXS9FKFJoAXHlPQE5qidKr8xxmxF5ezhmjGB0gjyjXIIkbSEnBg==