[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/envoyproxy/go-control-plane"
  version = "v0.9.0"

[[override]]
  version = "1.3.2"
  name = "github.com/golang/protobuf"